### ISSUE TITLE
Add AmazonCognitoReadOnly permission to the elasticbeanstalk user

### ISSUE THREAD

**Issue by AyalWein** [MoveoTech/terraform-aws-rest-api-architecture#231]

**Comment by EliranMoveo** [comment]
Do you need a write permission? Can you add all the permissions you added manually, and I'll add them

**Comment by NirK8** [comment]
> Do you need a write permission? Can you add all the permissions you added manually, and I'll add them

arn:aws:iam::aws:policy/AmazonCognitoReadOnly
